items:
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  id: EnvironmentPermissionAccess
  parent: System.Security.Permissions
  children:
  - System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.Read
  - System.Security.Permissions.EnvironmentPermissionAccess.Write
  href: System.Security.Permissions.EnvironmentPermissionAccess.yml
  name: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
    path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
    startLine: 12
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Specifies access to environment variables.
  syntax:
    content: public enum EnvironmentPermissionAccess
    content.vb: Public Enum EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  id: NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  href: System.Security.Permissions.EnvironmentPermissionAccess.yml
  name: NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
    startLine: 17
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: No access to environment variables. @'System.Security.Permissions.EnvironmentPermissionAccess.NoAccess' represents no valid @'System.Security.Permissions.EnvironmentPermissionAccess' values and causes an @'System.ArgumentException' when used as the parameter for @'System.Security.Permissions.EnvironmentPermission.GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)', which expects a single value.
  syntax:
    content: NoAccess = 0
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  href: System.Security.Permissions.EnvironmentPermissionAccess.yml
  name: Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
    startLine: 18
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Only read access to environment variables is specified. Changing, deleting and creating environment variables is not included in this access level.
  syntax:
    content: Read = 1
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  href: System.Security.Permissions.EnvironmentPermissionAccess.yml
  name: Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
    startLine: 19
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: Only write access to environment variables is specified. Write access includes creating and deleting environment variables as well as changing existing values. Reading environment variables is not included in this access level.
  syntax:
    content: Write = 2
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  id: AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  href: System.Security.Permissions.EnvironmentPermissionAccess.yml
  name: AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Security/Permissions/EnvironmentPermission.cs
    startLine: 20
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: '@''System.Security.Permissions.EnvironmentPermissionAccess.Read'' and @''System.Security.Permissions.EnvironmentPermissionAccess.Write'' access to environment variables. @''System.Security.Permissions.EnvironmentPermissionAccess.AllAccess'' represents multiple @''System.Security.Permissions.EnvironmentPermissionAccess'' values and causes an @''System.ArgumentException'' when used as the *flag* parameter for the @''System.Security.Permissions.EnvironmentPermission.GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)'' method, which expects a single value.'
  syntax:
    content: AllAccess = 3
references:
- uid: System.Security.Permissions
  isExternal: false
  name: System.Security.Permissions
  fullName: System.Security.Permissions
  type: Namespace
