items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  href: System.Configuration.Assemblies.AssemblyVersionCompatibility.yml
  name: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  source:
    remote: &o0
      path: src/mscorlib/src/System/Configuration/Assemblies/AssemblyVersionCompatibility.cs
      branch: master
      repo: https://github.com/chenkennt/coreclr.git
    path: src/mscorlib/src/System/Configuration/Assemblies/AssemblyVersionCompatibility.cs
    startLine: 14
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: Defines the different types of assembly version compatibility. This feature is not available in version 1.0 of the .NET Framework.
  syntax:
    content: public enum AssemblyVersionCompatibility
    content.vb: Public Enum AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  href: System.Configuration.Assemblies.AssemblyVersionCompatibility.yml
  name: SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Configuration/Assemblies/AssemblyVersionCompatibility.cs
    startLine: 18
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: The assembly cannot execute with other versions if they are executing on the same machine.
  syntax:
    content: SameMachine = 1
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  href: System.Configuration.Assemblies.AssemblyVersionCompatibility.yml
  name: SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Configuration/Assemblies/AssemblyVersionCompatibility.cs
    startLine: 19
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: The assembly cannot execute with other versions if they are executing in the same process.
  syntax:
    content: SameProcess = 2
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  href: System.Configuration.Assemblies.AssemblyVersionCompatibility.yml
  name: SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  source:
    remote: *o0
    path: src/mscorlib/src/System/Configuration/Assemblies/AssemblyVersionCompatibility.cs
    startLine: 20
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: The assembly cannot execute with other versions if they are executing in the same application domain.
  syntax:
    content: SameDomain = 3
references:
- uid: System.Configuration.Assemblies
  isExternal: false
  name: System.Configuration.Assemblies
  fullName: System.Configuration.Assemblies
  type: Namespace
