items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.CodeAccessPermission
  - System.Security.HostProtectionException
  - System.Security.HostSecurityManager
  - System.Security.HostSecurityManagerOptions
  - System.Security.IEvidenceFactory
  - System.Security.IPermission
  - System.Security.ISecurityEncodable
  - System.Security.ISecurityPolicyEncodable
  - System.Security.IStackWalk
  - System.Security.NamedPermissionSet
  - System.Security.PartialTrustVisibilityLevel
  - System.Security.PermissionSet
  - System.Security.PolicyLevelType
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  - System.Security.SecurityContextSource
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityElement
  - System.Security.SecurityException
  - System.Security.SecurityManager
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityState
  - System.Security.SecurityTransparentAttribute
  - System.Security.SecurityTreatAsSafeAttribute
  - System.Security.SecurityZone
  - System.Security.SuppressUnmanagedCodeSecurityAttribute
  - System.Security.UnverifiableCodeAttribute
  - System.Security.VerificationException
  - System.Security.XmlSyntaxException
  href: System.Security.yml
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
      branch: master
      repo: https://github.com/chenkennt/corefx.git
    path: src/System.Security.SecureString/src/System/Security/SafeBSTRHandle.cs
    startLine: 6
  assemblies:
  - System.Security.SecureString
  summary: The @'System.Security' namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
references:
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: false
  href: System.Security.SecureString.yml
  name: SecureString
  fullName: System.Security.SecureString
  type: Class
  summary: Represents text that should be kept confidential, such as by deleting it from computer memory when no longer needed. This class cannot be inherited.
- uid: System.Security.SecureStringMarshal
  isExternal: false
  href: System.Security.SecureStringMarshal.yml
  name: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
  type: Class
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityElement.yml
  name: SecurityElement
  fullName: System.Security.SecurityElement
  type: Class
  summary: Represents the XML object model for encoding security objects. This class cannot be inherited.
- uid: System.Security.XmlSyntaxException
  isExternal: false
  href: System.Security.XmlSyntaxException.yml
  name: XmlSyntaxException
  fullName: System.Security.XmlSyntaxException
  type: Class
  summary: The exception that is thrown when there is a syntax error in XML parsing. This class cannot be inherited.
- uid: System.Security.SuppressUnmanagedCodeSecurityAttribute
  isExternal: false
  href: System.Security.SuppressUnmanagedCodeSecurityAttribute.yml
  name: SuppressUnmanagedCodeSecurityAttribute
  fullName: System.Security.SuppressUnmanagedCodeSecurityAttribute
  type: Class
  summary: Allows managed code to call into unmanaged code without a stack walk. This class cannot be inherited.
- uid: System.Security.UnverifiableCodeAttribute
  isExternal: false
  href: System.Security.UnverifiableCodeAttribute.yml
  name: UnverifiableCodeAttribute
  fullName: System.Security.UnverifiableCodeAttribute
  type: Class
  summary: Marks modules containing unverifiable code. This class cannot be inherited.
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  href: System.Security.AllowPartiallyTrustedCallersAttribute.yml
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
  type: Class
  summary: Allows an assembly to be called by partially trusted code. Without this declaration, only fully trusted callers are able to use the assembly. This class cannot be inherited.
- uid: System.Security.PartialTrustVisibilityLevel
  parent: System.Security
  isExternal: false
  href: System.Security.PartialTrustVisibilityLevel.yml
  name: PartialTrustVisibilityLevel
  fullName: System.Security.PartialTrustVisibilityLevel
  type: Enum
  summary: Specifies the default partial-trust visibility for code that is marked with the @'System.Security.AllowPartiallyTrustedCallersAttribute' (APTCA) attribute.
- uid: System.Security.SecurityCriticalAttribute
  isExternal: false
  href: System.Security.SecurityCriticalAttribute.yml
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
  type: Class
  summary: Specifies that code or an assembly performs security-critical operations.
- uid: System.Security.SecurityTreatAsSafeAttribute
  isExternal: false
  href: System.Security.SecurityTreatAsSafeAttribute.yml
  name: SecurityTreatAsSafeAttribute
  fullName: System.Security.SecurityTreatAsSafeAttribute
  type: Class
  summary: Identifies which of the nonpublic @'System.Security.SecurityCriticalAttribute' members are accessible by transparent code within the assembly.
- uid: System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  href: System.Security.SecuritySafeCriticalAttribute.yml
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
  type: Class
  summary: Identifies types or members as security-critical and safely accessible by transparent code.
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  href: System.Security.SecurityTransparentAttribute.yml
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
  type: Class
  summary: Specifies that an assembly cannot cause an elevation of privilege.
- uid: System.Security.CodeAccessPermission
  parent: System.Security
  isExternal: false
  href: System.Security.CodeAccessPermission.yml
  name: CodeAccessPermission
  fullName: System.Security.CodeAccessPermission
  type: Class
  summary: Defines the underlying structure of all code access permissions.
- uid: System.Security.IEvidenceFactory
  parent: System.Security
  isExternal: false
  href: System.Security.IEvidenceFactory.yml
  name: IEvidenceFactory
  fullName: System.Security.IEvidenceFactory
  type: Interface
  summary: Gets an object's @'System.Security.Policy.Evidence'.
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  href: System.Security.IPermission.yml
  name: IPermission
  fullName: System.Security.IPermission
  type: Interface
  summary: Defines methods implemented by permission types.
- uid: System.Security.ISecurityEncodable
  parent: System.Security
  isExternal: false
  href: System.Security.ISecurityEncodable.yml
  name: ISecurityEncodable
  fullName: System.Security.ISecurityEncodable
  type: Interface
  summary: Defines the methods that convert permission object state to and from XML element representation.
- uid: System.Security.ISecurityPolicyEncodable
  parent: System.Security
  isExternal: false
  href: System.Security.ISecurityPolicyEncodable.yml
  name: ISecurityPolicyEncodable
  fullName: System.Security.ISecurityPolicyEncodable
  type: Interface
  summary: Supports the methods that convert permission object state to and from an XML element representation.
- uid: System.Security.IStackWalk
  parent: System.Security
  isExternal: false
  href: System.Security.IStackWalk.yml
  name: IStackWalk
  fullName: System.Security.IStackWalk
  type: Interface
  summary: Manages the stack walk that determines whether all callers in the call stack have the required permissions to access a protected resource.
- uid: System.Security.HostSecurityManagerOptions
  parent: System.Security
  isExternal: false
  href: System.Security.HostSecurityManagerOptions.yml
  name: HostSecurityManagerOptions
  fullName: System.Security.HostSecurityManagerOptions
  type: Enum
  summary: Specifies the security policy components to be used by the host security manager.
- uid: System.Security.HostSecurityManager
  isExternal: false
  href: System.Security.HostSecurityManager.yml
  name: HostSecurityManager
  fullName: System.Security.HostSecurityManager
  type: Class
  summary: Allows the control and customization of security behavior for application domains.
- uid: System.Security.NamedPermissionSet
  isExternal: false
  href: System.Security.NamedPermissionSet.yml
  name: NamedPermissionSet
  fullName: System.Security.NamedPermissionSet
  type: Class
  summary: Defines a permission set that has a name and description associated with it. This class cannot be inherited.
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  href: System.Security.PermissionSet.yml
  name: PermissionSet
  fullName: System.Security.PermissionSet
  type: Class
  summary: Represents a collection that can contain many different types of permissions.
- uid: System.Security.SecurityContextSource
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityContextSource.yml
  name: SecurityContextSource
  fullName: System.Security.SecurityContextSource
  type: Enum
  summary: Identifies the source for the security context.
- uid: System.Security.SecurityException
  isExternal: false
  href: System.Security.SecurityException.yml
  name: SecurityException
  fullName: System.Security.SecurityException
  type: Class
  summary: The exception that is thrown when a security error is detected.
- uid: System.Security.SecurityState
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityState.yml
  name: SecurityState
  fullName: System.Security.SecurityState
  type: Class
  summary: Provides a base class for requesting the security status of an action from the @'System.AppDomainManager' object.
- uid: System.Security.HostProtectionException
  isExternal: false
  href: System.Security.HostProtectionException.yml
  name: HostProtectionException
  fullName: System.Security.HostProtectionException
  type: Class
  summary: The exception that is thrown when a denied host resource is detected.
- uid: System.Security.PolicyLevelType
  parent: System.Security
  isExternal: false
  href: System.Security.PolicyLevelType.yml
  name: PolicyLevelType
  fullName: System.Security.PolicyLevelType
  type: Enum
  summary: Specifies the type of a managed code policy level.
- uid: System.Security.SecurityManager
  isExternal: false
  href: System.Security.SecurityManager.yml
  name: SecurityManager
  fullName: System.Security.SecurityManager
  type: Class
  summary: Provides the main access point for classes interacting with the security system. This class cannot be inherited.
- uid: System.Security.SecurityZone
  parent: System.Security
  isExternal: false
  href: System.Security.SecurityZone.yml
  name: SecurityZone
  fullName: System.Security.SecurityZone
  type: Enum
  summary: Defines the integer values corresponding to security zones used by security policy.
- uid: System.Security.VerificationException
  isExternal: false
  href: System.Security.VerificationException.yml
  name: VerificationException
  fullName: System.Security.VerificationException
  type: Class
  summary: The exception that is thrown when the security policy requires code to be type safe and the verification process is unable to verify that the code is type safe.
- uid: System.Security
  isExternal: false
  name: System.Security
  fullName: System.Security
  type: Namespace
